// ===== HIRAGANA =====
const HIRAGANA = [
  { char:'あ', romaji:'a',   group:'Vowel',   words:[{w:'あめ',r:'ame',m:'rain'},{w:'あお',r:'ao',m:'blue'},{w:'あさ',r:'asa',m:'morning'}] },
  { char:'い', romaji:'i',   group:'Vowel',   words:[{w:'いぬ',r:'inu',m:'dog'},{w:'いえ',r:'ie',m:'house'},{w:'いと',r:'ito',m:'thread'}] },
  { char:'う', romaji:'u',   group:'Vowel',   words:[{w:'うみ',r:'umi',m:'sea'},{w:'うた',r:'uta',m:'song'},{w:'うし',r:'ushi',m:'cow'}] },
  { char:'え', romaji:'e',   group:'Vowel',   words:[{w:'えき',r:'eki',m:'station'},{w:'えん',r:'en',m:'yen'},{w:'えほん',r:'ehon',m:'picture book'}] },
  { char:'お', romaji:'o',   group:'Vowel',   words:[{w:'おか',r:'oka',m:'hill'},{w:'おに',r:'oni',m:'demon'},{w:'おと',r:'oto',m:'sound'}] },
  { char:'か', romaji:'ka',  group:'K-row',   words:[{w:'かさ',r:'kasa',m:'umbrella'},{w:'かわ',r:'kawa',m:'river'},{w:'かに',r:'kani',m:'crab'}] },
  { char:'き', romaji:'ki',  group:'K-row',   words:[{w:'きつね',r:'kitsune',m:'fox'},{w:'きく',r:'kiku',m:'chrysanthemum'},{w:'きもの',r:'kimono',m:'kimono'}] },
  { char:'く', romaji:'ku',  group:'K-row',   words:[{w:'くも',r:'kumo',m:'cloud'},{w:'くち',r:'kuchi',m:'mouth'},{w:'くつ',r:'kutsu',m:'shoes'}] },
  { char:'け', romaji:'ke',  group:'K-row',   words:[{w:'けむり',r:'kemuri',m:'smoke'},{w:'けいと',r:'keito',m:'wool'},{w:'けが',r:'kega',m:'injury'}] },
  { char:'こ', romaji:'ko',  group:'K-row',   words:[{w:'こえ',r:'koe',m:'voice'},{w:'こい',r:'koi',m:'carp'},{w:'こころ',r:'kokoro',m:'heart'}] },
  { char:'さ', romaji:'sa',  group:'S-row',   words:[{w:'さくら',r:'sakura',m:'cherry blossom'},{w:'さかな',r:'sakana',m:'fish'},{w:'さむい',r:'samui',m:'cold'}] },
  { char:'し', romaji:'shi', group:'S-row',   words:[{w:'しろ',r:'shiro',m:'white/castle'},{w:'しお',r:'shio',m:'salt'},{w:'しずか',r:'shizuka',m:'quiet'}] },
  { char:'す', romaji:'su',  group:'S-row',   words:[{w:'すし',r:'sushi',m:'sushi'},{w:'すな',r:'suna',m:'sand'},{w:'すき',r:'suki',m:'like'}] },
  { char:'せ', romaji:'se',  group:'S-row',   words:[{w:'せかい',r:'sekai',m:'world'},{w:'せんせい',r:'sensei',m:'teacher'},{w:'せみ',r:'semi',m:'cicada'}] },
  { char:'そ', romaji:'so',  group:'S-row',   words:[{w:'そら',r:'sora',m:'sky'},{w:'そば',r:'soba',m:'soba noodles'},{w:'そと',r:'soto',m:'outside'}] },
  { char:'た', romaji:'ta',  group:'T-row',   words:[{w:'たこ',r:'tako',m:'octopus'},{w:'たき',r:'taki',m:'waterfall'},{w:'たまご',r:'tamago',m:'egg'}] },
  { char:'ち', romaji:'chi', group:'T-row',   words:[{w:'ちず',r:'chizu',m:'map'},{w:'ちから',r:'chikara',m:'strength'},{w:'ちょう',r:'chou',m:'butterfly'}] },
  { char:'つ', romaji:'tsu', group:'T-row',   words:[{w:'つき',r:'tsuki',m:'moon'},{w:'つる',r:'tsuru',m:'crane'},{w:'つゆ',r:'tsuyu',m:'rainy season'}] },
  { char:'て', romaji:'te',  group:'T-row',   words:[{w:'てがみ',r:'tegami',m:'letter'},{w:'てら',r:'tera',m:'temple'},{w:'てんき',r:'tenki',m:'weather'}] },
  { char:'と', romaji:'to',  group:'T-row',   words:[{w:'とり',r:'tori',m:'bird'},{w:'とけい',r:'tokei',m:'clock'},{w:'ともだち',r:'tomodachi',m:'friend'}] },
  { char:'な', romaji:'na',  group:'N-row',   words:[{w:'なみ',r:'nami',m:'wave'},{w:'なつ',r:'natsu',m:'summer'},{w:'なまえ',r:'namae',m:'name'}] },
  { char:'に', romaji:'ni',  group:'N-row',   words:[{w:'にじ',r:'niji',m:'rainbow'},{w:'にわ',r:'niwa',m:'garden'},{w:'にほん',r:'nihon',m:'Japan'}] },
  { char:'ぬ', romaji:'nu',  group:'N-row',   words:[{w:'ぬの',r:'nuno',m:'cloth'},{w:'ぬま',r:'numa',m:'swamp'},{w:'ぬいぐるみ',r:'nuigurumi',m:'stuffed toy'}] },
  { char:'ね', romaji:'ne',  group:'N-row',   words:[{w:'ねこ',r:'neko',m:'cat'},{w:'ねむい',r:'nemui',m:'sleepy'},{w:'ねつ',r:'netsu',m:'fever'}] },
  { char:'の', romaji:'no',  group:'N-row',   words:[{w:'のり',r:'nori',m:'seaweed'},{w:'のはら',r:'nohara',m:'field'},{w:'のみもの',r:'nomimono',m:'drink'}] },
  { char:'は', romaji:'ha',  group:'H-row',   words:[{w:'はな',r:'hana',m:'flower'},{w:'はる',r:'haru',m:'spring'},{w:'はし',r:'hashi',m:'chopsticks'}] },
  { char:'ひ', romaji:'hi',  group:'H-row',   words:[{w:'ひと',r:'hito',m:'person'},{w:'ひかり',r:'hikari',m:'light'},{w:'ひまわり',r:'himawari',m:'sunflower'}] },
  { char:'ふ', romaji:'fu',  group:'H-row',   words:[{w:'ふゆ',r:'fuyu',m:'winter'},{w:'ふね',r:'fune',m:'boat'},{w:'ふじ',r:'fuji',m:'Mt. Fuji'}] },
  { char:'へ', romaji:'he',  group:'H-row',   words:[{w:'へや',r:'heya',m:'room'},{w:'へび',r:'hebi',m:'snake'},{w:'へいわ',r:'heiwa',m:'peace'}] },
  { char:'ほ', romaji:'ho',  group:'H-row',   words:[{w:'ほし',r:'hoshi',m:'star'},{w:'ほん',r:'hon',m:'book'},{w:'ほたる',r:'hotaru',m:'firefly'}] },
  { char:'ま', romaji:'ma',  group:'M-row',   words:[{w:'まど',r:'mado',m:'window'},{w:'まつり',r:'matsuri',m:'festival'},{w:'まち',r:'machi',m:'town'}] },
  { char:'み', romaji:'mi',  group:'M-row',   words:[{w:'みず',r:'mizu',m:'water'},{w:'みち',r:'michi',m:'road'},{w:'みかん',r:'mikan',m:'mandarin'}] },
  { char:'む', romaji:'mu',  group:'M-row',   words:[{w:'むし',r:'mushi',m:'insect'},{w:'むら',r:'mura',m:'village'},{w:'むすめ',r:'musume',m:'daughter'}] },
  { char:'め', romaji:'me',  group:'M-row',   words:[{w:'めだか',r:'medaka',m:'killifish'},{w:'めがね',r:'megane',m:'glasses'},{w:'めぐみ',r:'megumi',m:'blessing'}] },
  { char:'も', romaji:'mo',  group:'M-row',   words:[{w:'もり',r:'mori',m:'forest'},{w:'もも',r:'momo',m:'peach'},{w:'もち',r:'mochi',m:'rice cake'}] },
  { char:'や', romaji:'ya',  group:'Y-row',   words:[{w:'やま',r:'yama',m:'mountain'},{w:'やさい',r:'yasai',m:'vegetable'},{w:'やきとり',r:'yakitori',m:'grilled chicken'}] },
  { char:'ゆ', romaji:'yu',  group:'Y-row',   words:[{w:'ゆき',r:'yuki',m:'snow'},{w:'ゆめ',r:'yume',m:'dream'},{w:'ゆびわ',r:'yubiwa',m:'ring'}] },
  { char:'よ', romaji:'yo',  group:'Y-row',   words:[{w:'よる',r:'yoru',m:'night'},{w:'よみ',r:'yomi',m:'reading'},{w:'ようかい',r:'youkai',m:'spirit'}] },
  { char:'ら', romaji:'ra',  group:'R-row',   words:[{w:'らくだ',r:'rakuda',m:'camel'},{w:'らいねん',r:'rainen',m:'next year'},{w:'らんぷ',r:'ranpu',m:'lamp'}] },
  { char:'り', romaji:'ri',  group:'R-row',   words:[{w:'りんご',r:'ringo',m:'apple'},{w:'りゅう',r:'ryuu',m:'dragon'},{w:'りす',r:'risu',m:'squirrel'}] },
  { char:'る', romaji:'ru',  group:'R-row',   words:[{w:'るびー',r:'rubii',m:'ruby'},{w:'るすばん',r:'rusuban',m:'house-sitting'},{w:'るーぷ',r:'ruupu',m:'loop'}] },
  { char:'れ', romaji:'re',  group:'R-row',   words:[{w:'れんこん',r:'renkon',m:'lotus root'},{w:'れいぞうこ',r:'reizouko',m:'fridge'},{w:'れきし',r:'rekishi',m:'history'}] },
  { char:'ろ', romaji:'ro',  group:'R-row',   words:[{w:'ろうそく',r:'rousoku',m:'candle'},{w:'ろば',r:'roba',m:'donkey'},{w:'ろっく',r:'rokku',m:'rock music'}] },
  { char:'わ', romaji:'wa',  group:'W-row',   words:[{w:'わに',r:'wani',m:'crocodile'},{w:'わた',r:'wata',m:'cotton'},{w:'わかば',r:'wakaba',m:'young leaves'}] },
  { char:'を', romaji:'wo',  group:'W-row',   words:[{w:'(object marker)',r:'wo',m:'particle を'}] },
  { char:'ん', romaji:'n',   group:'N-nasal', words:[{w:'(nasal sound)',r:'n',m:'used at end of syllables'}] },

  // ── Dakuten (voiced) ──
  { char:'が', romaji:'ga',  group:'Dakuten', words:[{w:'がっこう',r:'gakkou',m:'school'},{w:'がいこく',r:'gaikoku',m:'foreign country'},{w:'がまん',r:'gaman',m:'patience'}] },
  { char:'ぎ', romaji:'gi',  group:'Dakuten', words:[{w:'ぎんこう',r:'ginkou',m:'bank'},{w:'ぎゅうにゅう',r:'gyuunyuu',m:'milk'},{w:'ぎもん',r:'gimon',m:'question'}] },
  { char:'ぐ', romaji:'gu',  group:'Dakuten', words:[{w:'ぐあい',r:'guai',m:'condition'},{w:'ぐんたい',r:'guntai',m:'army'},{w:'ぐち',r:'guchi',m:'complaint'}] },
  { char:'げ', romaji:'ge',  group:'Dakuten', words:[{w:'げんき',r:'genki',m:'healthy/energetic'},{w:'げつようび',r:'getsuyoubi',m:'Monday'},{w:'げいじゅつ',r:'geijutsu',m:'art'}] },
  { char:'ご', romaji:'go',  group:'Dakuten', words:[{w:'ごはん',r:'gohan',m:'rice/meal'},{w:'ごご',r:'gogo',m:'afternoon'},{w:'ごみ',r:'gomi',m:'trash'}] },
  { char:'ざ', romaji:'za',  group:'Dakuten', words:[{w:'ざっし',r:'zasshi',m:'magazine'},{w:'ざいりょう',r:'zairyou',m:'material'},{w:'ざんねん',r:'zannen',m:'unfortunate'}] },
  { char:'じ', romaji:'ji',  group:'Dakuten', words:[{w:'じかん',r:'jikan',m:'time'},{w:'じてんしゃ',r:'jitensha',m:'bicycle'},{w:'じしん',r:'jishin',m:'earthquake'}] },
  { char:'ず', romaji:'zu',  group:'Dakuten', words:[{w:'ずっと',r:'zutto',m:'all along'},{w:'ずかん',r:'zukan',m:'illustrated book'},{w:'ずのう',r:'zunou',m:'brain/intellect'}] },
  { char:'ぜ', romaji:'ze',  group:'Dakuten', words:[{w:'ぜんぶ',r:'zenbu',m:'all/everything'},{w:'ぜったい',r:'zettai',m:'absolutely'},{w:'ぜいきん',r:'zeikin',m:'tax'}] },
  { char:'ぞ', romaji:'zo',  group:'Dakuten', words:[{w:'ぞう',r:'zou',m:'elephant'},{w:'ぞうきん',r:'zoukin',m:'cleaning cloth'},{w:'ぞくぞく',r:'zokuzoku',m:'thrilling'}] },
  { char:'だ', romaji:'da',  group:'Dakuten', words:[{w:'だいがく',r:'daigaku',m:'university'},{w:'だいどころ',r:'daidokoro',m:'kitchen'},{w:'だれ',r:'dare',m:'who'}] },
  { char:'ぢ', romaji:'di',  group:'Dakuten', words:[{w:'はなぢ',r:'hanaji',m:'nosebleed'},{w:'ちぢむ',r:'chijimu',m:'to shrink'}] },
  { char:'づ', romaji:'du',  group:'Dakuten', words:[{w:'つづく',r:'tsuzuku',m:'to continue'},{w:'こづつみ',r:'kozutsumi',m:'parcel'}] },
  { char:'で', romaji:'de',  group:'Dakuten', words:[{w:'でんしゃ',r:'densha',m:'train'},{w:'でぐち',r:'deguchi',m:'exit'},{w:'でんわ',r:'denwa',m:'telephone'}] },
  { char:'ど', romaji:'do',  group:'Dakuten', words:[{w:'どうぶつ',r:'doubutsu',m:'animal'},{w:'どこ',r:'doko',m:'where'},{w:'どようび',r:'doyoubi',m:'Saturday'}] },
  { char:'ば', romaji:'ba',  group:'Dakuten', words:[{w:'ばしょ',r:'basho',m:'place'},{w:'ばんごはん',r:'bangohan',m:'dinner'},{w:'ばら',r:'bara',m:'rose'}] },
  { char:'び', romaji:'bi',  group:'Dakuten', words:[{w:'びょういん',r:'byouin',m:'hospital'},{w:'びじゅつかん',r:'bijutsukan',m:'art museum'},{w:'びっくり',r:'bikkuri',m:'surprised'}] },
  { char:'ぶ', romaji:'bu',  group:'Dakuten', words:[{w:'ぶどう',r:'budou',m:'grapes'},{w:'ぶんか',r:'bunka',m:'culture'},{w:'ぶた',r:'buta',m:'pig'}] },
  { char:'べ', romaji:'be',  group:'Dakuten', words:[{w:'べんきょう',r:'benkyou',m:'study'},{w:'べんとう',r:'bentou',m:'bento box'},{w:'べや',r:'beya',m:'room (sumo)'}] },
  { char:'ぼ', romaji:'bo',  group:'Dakuten', words:[{w:'ぼうし',r:'boushi',m:'hat'},{w:'ぼく',r:'boku',m:'I (male)'},{w:'ぼたん',r:'botan',m:'button/peony'}] },

  // ── Handakuten (semi-voiced) ──
  { char:'ぱ', romaji:'pa',  group:'Handakuten', words:[{w:'ぱん',r:'pan',m:'bread'},{w:'ぱーてぃー',r:'paatii',m:'party'},{w:'ぱそこん',r:'pasokon',m:'PC'}] },
  { char:'ぴ', romaji:'pi',  group:'Handakuten', words:[{w:'ぴあの',r:'piano',m:'piano'},{w:'ぴかぴか',r:'pikapika',m:'sparkling'},{w:'ぴんく',r:'pinku',m:'pink'}] },
  { char:'ぷ', romaji:'pu',  group:'Handakuten', words:[{w:'ぷーる',r:'puuru',m:'pool'},{w:'ぷれぜんと',r:'purezento',m:'present'},{w:'ぷりん',r:'purin',m:'pudding'}] },
  { char:'ぺ', romaji:'pe',  group:'Handakuten', words:[{w:'ぺん',r:'pen',m:'pen'},{w:'ぺっと',r:'petto',m:'pet'},{w:'ぺーじ',r:'peeji',m:'page'}] },
  { char:'ぽ', romaji:'po',  group:'Handakuten', words:[{w:'ぽすと',r:'posuto',m:'mailbox'},{w:'ぽけっと',r:'poketto',m:'pocket'},{w:'ぽいんと',r:'pointo',m:'point'}] },

  // ── Combo / Youon ──
  { char:'きゃ', romaji:'kya', group:'Combo', words:[{w:'きゃく',r:'kyaku',m:'guest/customer'},{w:'きゃんぷ',r:'kyanpu',m:'camping'}] },
  { char:'きゅ', romaji:'kyu', group:'Combo', words:[{w:'きゅうり',r:'kyuuri',m:'cucumber'},{w:'きゅうきゅうしゃ',r:'kyuukyuusha',m:'ambulance'}] },
  { char:'きょ', romaji:'kyo', group:'Combo', words:[{w:'きょうしつ',r:'kyoushitsu',m:'classroom'},{w:'きょねん',r:'kyonen',m:'last year'}] },
  { char:'しゃ', romaji:'sha', group:'Combo', words:[{w:'しゃしん',r:'shashin',m:'photo'},{w:'しゃわー',r:'shawaa',m:'shower'}] },
  { char:'しゅ', romaji:'shu', group:'Combo', words:[{w:'しゅくだい',r:'shukudai',m:'homework'},{w:'しゅみ',r:'shumi',m:'hobby'}] },
  { char:'しょ', romaji:'sho', group:'Combo', words:[{w:'しょくじ',r:'shokuji',m:'meal'},{w:'しょうがっこう',r:'shougakkou',m:'elementary school'}] },
  { char:'ちゃ', romaji:'cha', group:'Combo', words:[{w:'おちゃ',r:'ocha',m:'tea'},{w:'ちゃいろ',r:'chairo',m:'brown'}] },
  { char:'ちゅ', romaji:'chu', group:'Combo', words:[{w:'ちゅうがっこう',r:'chuugakkou',m:'middle school'},{w:'ちゅうしゃ',r:'chuusha',m:'injection'}] },
  { char:'ちょ', romaji:'cho', group:'Combo', words:[{w:'ちょうちょ',r:'choucho',m:'butterfly'},{w:'ちょっと',r:'chotto',m:'a little'}] },
  { char:'にゃ', romaji:'nya', group:'Combo', words:[{w:'にゃんこ',r:'nyanko',m:'kitty'},{w:'にゃー',r:'nyaa',m:'meow'}] },
  { char:'にゅ', romaji:'nyu', group:'Combo', words:[{w:'にゅうがく',r:'nyuugaku',m:'school enrollment'},{w:'にゅうす',r:'nyuusu',m:'news'}] },
  { char:'にょ', romaji:'nyo', group:'Combo', words:[{w:'にょろにょろ',r:'nyoronyoro',m:'wriggling'}] },
  { char:'ひゃ', romaji:'hya', group:'Combo', words:[{w:'ひゃく',r:'hyaku',m:'hundred'},{w:'ひゃくえん',r:'hyakuen',m:'100 yen'}] },
  { char:'ひゅ', romaji:'hyu', group:'Combo', words:[{w:'ひゅーひゅー',r:'hyuuhyuu',m:'whistling sound'}] },
  { char:'ひょ', romaji:'hyo', group:'Combo', words:[{w:'ひょう',r:'hyou',m:'hail/leopard'},{w:'ひょうき',r:'hyouki',m:'notation'}] },
  { char:'みゃ', romaji:'mya', group:'Combo', words:[{w:'みゃく',r:'myaku',m:'pulse'}] },
  { char:'みゅ', romaji:'myu', group:'Combo', words:[{w:'みゅーじっく',r:'myuujikku',m:'music'}] },
  { char:'みょ', romaji:'myo', group:'Combo', words:[{w:'みょうじ',r:'myouji',m:'surname'}] },
  { char:'りゃ', romaji:'rya', group:'Combo', words:[{w:'りゃくご',r:'ryakugo',m:'abbreviation'}] },
  { char:'りゅ', romaji:'ryu', group:'Combo', words:[{w:'りゅうがく',r:'ryuugaku',m:'study abroad'},{w:'りゅう',r:'ryuu',m:'dragon'}] },
  { char:'りょ', romaji:'ryo', group:'Combo', words:[{w:'りょこう',r:'ryokou',m:'travel'},{w:'りょうり',r:'ryouri',m:'cooking'}] },
  { char:'ぎゃ', romaji:'gya', group:'Combo', words:[{w:'ぎゃく',r:'gyaku',m:'reverse'},{w:'ぎゃくてん',r:'gyakuten',m:'reversal'}] },
  { char:'ぎゅ', romaji:'gyu', group:'Combo', words:[{w:'ぎゅうにゅう',r:'gyuunyuu',m:'milk'},{w:'ぎゅうにく',r:'gyuuniku',m:'beef'}] },
  { char:'ぎょ', romaji:'gyo', group:'Combo', words:[{w:'ぎょうざ',r:'gyouza',m:'dumplings'},{w:'ぎょうれつ',r:'gyouretsu',m:'queue'}] },
  { char:'じゃ', romaji:'ja',  group:'Combo', words:[{w:'じゃがいも',r:'jagaimo',m:'potato'},{w:'じゃんけん',r:'janken',m:'rock-paper-scissors'}] },
  { char:'じゅ', romaji:'ju',  group:'Combo', words:[{w:'じゅぎょう',r:'jugyou',m:'class/lesson'},{w:'じゅうしょ',r:'juusho',m:'address'}] },
  { char:'じょ', romaji:'jo',  group:'Combo', words:[{w:'じょうず',r:'jouzu',m:'skilled'},{w:'じょせい',r:'josei',m:'woman'}] },
  { char:'びゃ', romaji:'bya', group:'Combo', words:[{w:'びゃくや',r:'byakuya',m:'white night'}] },
  { char:'びゅ', romaji:'byu', group:'Combo', words:[{w:'びゅーびゅー',r:'byuubyuu',m:'whooshing sound'}] },
  { char:'びょ', romaji:'byo', group:'Combo', words:[{w:'びょういん',r:'byouin',m:'hospital'},{w:'びょうき',r:'byouki',m:'illness'}] },
  { char:'ぴゃ', romaji:'pya', group:'Combo', words:[{w:'ぴゃく',r:'pyaku',m:'(counter variant)'}] },
  { char:'ぴゅ', romaji:'pyu', group:'Combo', words:[{w:'ぴゅーぴゅー',r:'pyuupyuu',m:'whistling wind'}] },
  { char:'ぴょ', romaji:'pyo', group:'Combo', words:[{w:'ぴょんぴょん',r:'pyonpyon',m:'hopping'}] },
];

// ===== KATAKANA =====
const KATAKANA = [
  { char:'ア', romaji:'a',   group:'Vowel',   words:[{w:'アイス',r:'aisu',m:'ice cream'},{w:'アニメ',r:'anime',m:'anime'},{w:'アジア',r:'ajia',m:'Asia'}] },
  { char:'イ', romaji:'i',   group:'Vowel',   words:[{w:'イチゴ',r:'ichigo',m:'strawberry'},{w:'イルカ',r:'iruka',m:'dolphin'},{w:'インク',r:'inku',m:'ink'}] },
  { char:'ウ', romaji:'u',   group:'Vowel',   words:[{w:'ウサギ',r:'usagi',m:'rabbit'},{w:'ウイルス',r:'uirusu',m:'virus'},{w:'ウール',r:'uuru',m:'wool'}] },
  { char:'エ', romaji:'e',   group:'Vowel',   words:[{w:'エビ',r:'ebi',m:'shrimp'},{w:'エコ',r:'eko',m:'eco'},{w:'エンジン',r:'enjin',m:'engine'}] },
  { char:'オ', romaji:'o',   group:'Vowel',   words:[{w:'オレンジ',r:'orenji',m:'orange'},{w:'オオカミ',r:'ookami',m:'wolf'},{w:'オーブン',r:'oobun',m:'oven'}] },
  { char:'カ', romaji:'ka',  group:'K-row',   words:[{w:'カメラ',r:'kamera',m:'camera'},{w:'カフェ',r:'kafe',m:'café'},{w:'カレー',r:'karee',m:'curry'}] },
  { char:'キ', romaji:'ki',  group:'K-row',   words:[{w:'キツネ',r:'kitsune',m:'fox'},{w:'キャット',r:'kyatto',m:'cat'},{w:'キウイ',r:'kiui',m:'kiwi'}] },
  { char:'ク', romaji:'ku',  group:'K-row',   words:[{w:'クマ',r:'kuma',m:'bear'},{w:'クッキー',r:'kukkii',m:'cookie'},{w:'クラス',r:'kurasu',m:'class'}] },
  { char:'ケ', romaji:'ke',  group:'K-row',   words:[{w:'ケーキ',r:'keeki',m:'cake'},{w:'ケトル',r:'ketoru',m:'kettle'},{w:'ケガ',r:'kega',m:'injury'}] },
  { char:'コ', romaji:'ko',  group:'K-row',   words:[{w:'コーヒー',r:'koohii',m:'coffee'},{w:'コアラ',r:'koara',m:'koala'},{w:'コート',r:'kooto',m:'coat'}] },
  { char:'サ', romaji:'sa',  group:'S-row',   words:[{w:'サクラ',r:'sakura',m:'cherry blossom'},{w:'サラダ',r:'sarada',m:'salad'},{w:'サンタ',r:'santa',m:'Santa'}] },
  { char:'シ', romaji:'shi', group:'S-row',   words:[{w:'シロクマ',r:'shirokuma',m:'polar bear'},{w:'シャツ',r:'shatsu',m:'shirt'},{w:'シール',r:'shiiru',m:'sticker'}] },
  { char:'ス', romaji:'su',  group:'S-row',   words:[{w:'スシ',r:'sushi',m:'sushi'},{w:'スカート',r:'sukaato',m:'skirt'},{w:'スター',r:'sutaa',m:'star'}] },
  { char:'セ', romaji:'se',  group:'S-row',   words:[{w:'セーター',r:'seetaa',m:'sweater'},{w:'センス',r:'sensu',m:'sense'},{w:'セロリ',r:'serori',m:'celery'}] },
  { char:'ソ', romaji:'so',  group:'S-row',   words:[{w:'ソファ',r:'sofa',m:'sofa'},{w:'ソース',r:'soosu',m:'sauce'},{w:'ソング',r:'songu',m:'song'}] },
  { char:'タ', romaji:'ta',  group:'T-row',   words:[{w:'タコ',r:'tako',m:'octopus'},{w:'タオル',r:'taoru',m:'towel'},{w:'タピオカ',r:'tapioka',m:'tapioca'}] },
  { char:'チ', romaji:'chi', group:'T-row',   words:[{w:'チョコ',r:'choko',m:'chocolate'},{w:'チーズ',r:'chiizu',m:'cheese'},{w:'チューリップ',r:'chuurippu',m:'tulip'}] },
  { char:'ツ', romaji:'tsu', group:'T-row',   words:[{w:'ツナ',r:'tsuna',m:'tuna'},{w:'ツアー',r:'tsuaa',m:'tour'},{w:'ツリー',r:'tsurii',m:'tree'}] },
  { char:'テ', romaji:'te',  group:'T-row',   words:[{w:'テスト',r:'tesuto',m:'test'},{w:'テーブル',r:'teburu',m:'table'},{w:'テニス',r:'tenisu',m:'tennis'}] },
  { char:'ト', romaji:'to',  group:'T-row',   words:[{w:'トマト',r:'tomato',m:'tomato'},{w:'トースト',r:'toosuto',m:'toast'},{w:'トナカイ',r:'tonakai',m:'reindeer'}] },
  { char:'ナ', romaji:'na',  group:'N-row',   words:[{w:'ナイフ',r:'naifu',m:'knife'},{w:'ナッツ',r:'nattsu',m:'nuts'},{w:'ナース',r:'naaasu',m:'nurse'}] },
  { char:'ニ', romaji:'ni',  group:'N-row',   words:[{w:'ニンジン',r:'ninjin',m:'carrot'},{w:'ニュース',r:'nyuusu',m:'news'},{w:'ニット',r:'nitto',m:'knit'}] },
  { char:'ヌ', romaji:'nu',  group:'N-row',   words:[{w:'ヌードル',r:'nuudoru',m:'noodle'},{w:'ヌガー',r:'nugaa',m:'nougat'}] },
  { char:'ネ', romaji:'ne',  group:'N-row',   words:[{w:'ネコ',r:'neko',m:'cat'},{w:'ネクタイ',r:'nekutai',m:'necktie'},{w:'ネット',r:'netto',m:'net/internet'}] },
  { char:'ノ', romaji:'no',  group:'N-row',   words:[{w:'ノート',r:'nooto',m:'notebook'},{w:'ノイズ',r:'noizu',m:'noise'},{w:'ノック',r:'nokku',m:'knock'}] },
  { char:'ハ', romaji:'ha',  group:'H-row',   words:[{w:'ハート',r:'haato',m:'heart'},{w:'ハナ',r:'hana',m:'flower'},{w:'ハム',r:'hamu',m:'ham'}] },
  { char:'ヒ', romaji:'hi',  group:'H-row',   words:[{w:'ヒーロー',r:'hiiroo',m:'hero'},{w:'ヒマワリ',r:'himawari',m:'sunflower'},{w:'ヒント',r:'hinto',m:'hint'}] },
  { char:'フ', romaji:'fu',  group:'H-row',   words:[{w:'フルーツ',r:'furuutsu',m:'fruit'},{w:'フラワー',r:'furawaa',m:'flower'},{w:'フォーク',r:'fooku',m:'fork'}] },
  { char:'ヘ', romaji:'he',  group:'H-row',   words:[{w:'ヘア',r:'hea',m:'hair'},{w:'ヘルメット',r:'herumetto',m:'helmet'},{w:'ヘビ',r:'hebi',m:'snake'}] },
  { char:'ホ', romaji:'ho',  group:'H-row',   words:[{w:'ホテル',r:'hoteru',m:'hotel'},{w:'ホット',r:'hotto',m:'hot'},{w:'ホタル',r:'hotaru',m:'firefly'}] },
  { char:'マ', romaji:'ma',  group:'M-row',   words:[{w:'マンゴー',r:'mangoo',m:'mango'},{w:'マスク',r:'masuku',m:'mask'},{w:'マカロン',r:'makaron',m:'macaron'}] },
  { char:'ミ', romaji:'mi',  group:'M-row',   words:[{w:'ミルク',r:'miruku',m:'milk'},{w:'ミント',r:'minto',m:'mint'},{w:'ミラー',r:'miraa',m:'mirror'}] },
  { char:'ム', romaji:'mu',  group:'M-row',   words:[{w:'ムース',r:'muusu',m:'mousse'},{w:'ムービー',r:'muubii',m:'movie'},{w:'ムード',r:'muudo',m:'mood'}] },
  { char:'メ', romaji:'me',  group:'M-row',   words:[{w:'メロン',r:'meron',m:'melon'},{w:'メール',r:'meeru',m:'email'},{w:'メモ',r:'memo',m:'memo'}] },
  { char:'モ', romaji:'mo',  group:'M-row',   words:[{w:'モデル',r:'moderu',m:'model'},{w:'モンスター',r:'monsutaa',m:'monster'},{w:'モカ',r:'moka',m:'mocha'}] },
  { char:'ヤ', romaji:'ya',  group:'Y-row',   words:[{w:'ヤシ',r:'yashi',m:'palm tree'},{w:'ヤクルト',r:'yakuruto',m:'Yakult'},{w:'ヤード',r:'yaado',m:'yard'}] },
  { char:'ユ', romaji:'yu',  group:'Y-row',   words:[{w:'ユニコーン',r:'yunikoon',m:'unicorn'},{w:'ユーモア',r:'yuumoa',m:'humor'},{w:'ユリ',r:'yuri',m:'lily'}] },
  { char:'ヨ', romaji:'yo',  group:'Y-row',   words:[{w:'ヨーグルト',r:'yooguruto',m:'yogurt'},{w:'ヨット',r:'yotto',m:'yacht'},{w:'ヨガ',r:'yoga',m:'yoga'}] },
  { char:'ラ', romaji:'ra',  group:'R-row',   words:[{w:'ラーメン',r:'raamen',m:'ramen'},{w:'ラジオ',r:'rajio',m:'radio'},{w:'ラベンダー',r:'rabendaa',m:'lavender'}] },
  { char:'リ', romaji:'ri',  group:'R-row',   words:[{w:'リンゴ',r:'ringo',m:'apple'},{w:'リボン',r:'ribon',m:'ribbon'},{w:'リス',r:'risu',m:'squirrel'}] },
  { char:'ル', romaji:'ru',  group:'R-row',   words:[{w:'ルビー',r:'rubii',m:'ruby'},{w:'ルーム',r:'ruumu',m:'room'},{w:'ルール',r:'ruuru',m:'rule'}] },
  { char:'レ', romaji:'re',  group:'R-row',   words:[{w:'レモン',r:'remon',m:'lemon'},{w:'レース',r:'reesu',m:'lace/race'},{w:'レストラン',r:'resutoran',m:'restaurant'}] },
  { char:'ロ', romaji:'ro',  group:'R-row',   words:[{w:'ロボット',r:'robotto',m:'robot'},{w:'ロール',r:'rooru',m:'roll'},{w:'ロマンス',r:'romansu',m:'romance'}] },
  { char:'ワ', romaji:'wa',  group:'W-row',   words:[{w:'ワイン',r:'wain',m:'wine'},{w:'ワニ',r:'wani',m:'crocodile'},{w:'ワッフル',r:'waffuru',m:'waffle'}] },
  { char:'ヲ', romaji:'wo',  group:'W-row',   words:[{w:'(object marker)',r:'wo',m:'particle ヲ'}] },
  { char:'ン', romaji:'n',   group:'N-nasal', words:[{w:'(nasal sound)',r:'n',m:'used at end of syllables'}] },

  // ── Dakuten (voiced) ──
  { char:'ガ', romaji:'ga',  group:'Dakuten', words:[{w:'ガラス',r:'garasu',m:'glass'},{w:'ガソリン',r:'gasorin',m:'gasoline'},{w:'ガイド',r:'gaido',m:'guide'}] },
  { char:'ギ', romaji:'gi',  group:'Dakuten', words:[{w:'ギター',r:'gitaa',m:'guitar'},{w:'ギャップ',r:'gyappu',m:'gap'},{w:'ギフト',r:'gifuto',m:'gift'}] },
  { char:'グ', romaji:'gu',  group:'Dakuten', words:[{w:'グラス',r:'gurasu',m:'glass (cup)'},{w:'グループ',r:'guruupu',m:'group'},{w:'グリーン',r:'guriin',m:'green'}] },
  { char:'ゲ', romaji:'ge',  group:'Dakuten', words:[{w:'ゲーム',r:'geemu',m:'game'},{w:'ゲスト',r:'gesuto',m:'guest'},{w:'ゲート',r:'geeto',m:'gate'}] },
  { char:'ゴ', romaji:'go',  group:'Dakuten', words:[{w:'ゴリラ',r:'gorira',m:'gorilla'},{w:'ゴール',r:'gooru',m:'goal'},{w:'ゴム',r:'gomu',m:'rubber'}] },
  { char:'ザ', romaji:'za',  group:'Dakuten', words:[{w:'ザリガニ',r:'zarigani',m:'crayfish'},{w:'ザッパ',r:'zappa',m:'rough/sloppy'}] },
  { char:'ジ', romaji:'ji',  group:'Dakuten', words:[{w:'ジュース',r:'juusu',m:'juice'},{w:'ジャケット',r:'jaketto',m:'jacket'},{w:'ジム',r:'jimu',m:'gym'}] },
  { char:'ズ', romaji:'zu',  group:'Dakuten', words:[{w:'ズボン',r:'zubon',m:'trousers'},{w:'ズーム',r:'zuumu',m:'zoom'},{w:'ズッキーニ',r:'zukkiini',m:'zucchini'}] },
  { char:'ゼ', romaji:'ze',  group:'Dakuten', words:[{w:'ゼリー',r:'zerii',m:'jelly'},{w:'ゼロ',r:'zero',m:'zero'},{w:'ゼミ',r:'zemi',m:'seminar'}] },
  { char:'ゾ', romaji:'zo',  group:'Dakuten', words:[{w:'ゾウ',r:'zou',m:'elephant'},{w:'ゾーン',r:'zoon',m:'zone'},{w:'ゾンビ',r:'zonbi',m:'zombie'}] },
  { char:'ダ', romaji:'da',  group:'Dakuten', words:[{w:'ダンス',r:'dansu',m:'dance'},{w:'ダイヤ',r:'daiya',m:'diamond'},{w:'ダウン',r:'daun',m:'down'}] },
  { char:'ヂ', romaji:'di',  group:'Dakuten', words:[{w:'(rare voiced chi)',r:'di',m:'ヂ is rarely used'}] },
  { char:'ヅ', romaji:'du',  group:'Dakuten', words:[{w:'(rare voiced tsu)',r:'du',m:'ヅ is rarely used'}] },
  { char:'デ', romaji:'de',  group:'Dakuten', words:[{w:'デザート',r:'dezaato',m:'dessert'},{w:'デパート',r:'depaato',m:'department store'},{w:'デート',r:'deeto',m:'date'}] },
  { char:'ド', romaji:'do',  group:'Dakuten', words:[{w:'ドア',r:'doa',m:'door'},{w:'ドラゴン',r:'doragon',m:'dragon'},{w:'ドーナツ',r:'doonatsu',m:'donut'}] },
  { char:'バ', romaji:'ba',  group:'Dakuten', words:[{w:'バナナ',r:'banana',m:'banana'},{w:'バス',r:'basu',m:'bus'},{w:'バッグ',r:'baggu',m:'bag'}] },
  { char:'ビ', romaji:'bi',  group:'Dakuten', words:[{w:'ビール',r:'biiru',m:'beer'},{w:'ビデオ',r:'bideo',m:'video'},{w:'ビタミン',r:'bitamin',m:'vitamin'}] },
  { char:'ブ', romaji:'bu',  group:'Dakuten', words:[{w:'ブーツ',r:'buutsu',m:'boots'},{w:'ブランド',r:'burando',m:'brand'},{w:'ブルー',r:'buruu',m:'blue'}] },
  { char:'ベ', romaji:'be',  group:'Dakuten', words:[{w:'ベッド',r:'beddo',m:'bed'},{w:'ベルト',r:'beruto',m:'belt'},{w:'ベーカリー',r:'beekarii',m:'bakery'}] },
  { char:'ボ', romaji:'bo',  group:'Dakuten', words:[{w:'ボール',r:'booru',m:'ball'},{w:'ボタン',r:'botan',m:'button'},{w:'ボート',r:'booto',m:'boat'}] },

  // ── Handakuten (semi-voiced) ──
  { char:'パ', romaji:'pa',  group:'Handakuten', words:[{w:'パン',r:'pan',m:'bread'},{w:'パソコン',r:'pasokon',m:'PC'},{w:'パーティー',r:'paatii',m:'party'}] },
  { char:'ピ', romaji:'pi',  group:'Handakuten', words:[{w:'ピアノ',r:'piano',m:'piano'},{w:'ピザ',r:'piza',m:'pizza'},{w:'ピンク',r:'pinku',m:'pink'}] },
  { char:'プ', romaji:'pu',  group:'Handakuten', words:[{w:'プール',r:'puuru',m:'pool'},{w:'プレゼント',r:'purezento',m:'present'},{w:'プリン',r:'purin',m:'pudding'}] },
  { char:'ペ', romaji:'pe',  group:'Handakuten', words:[{w:'ペン',r:'pen',m:'pen'},{w:'ペット',r:'petto',m:'pet'},{w:'ページ',r:'peeji',m:'page'}] },
  { char:'ポ', romaji:'po',  group:'Handakuten', words:[{w:'ポスト',r:'posuto',m:'mailbox'},{w:'ポケット',r:'poketto',m:'pocket'},{w:'ポイント',r:'pointo',m:'point'}] },

  // ── Combo / Youon ──
  { char:'キャ', romaji:'kya', group:'Combo', words:[{w:'キャンプ',r:'kyanpu',m:'camping'},{w:'キャラクター',r:'kyarakutaa',m:'character'}] },
  { char:'キュ', romaji:'kyu', group:'Combo', words:[{w:'キュウリ',r:'kyuuri',m:'cucumber'},{w:'キューブ',r:'kyuubu',m:'cube'}] },
  { char:'キョ', romaji:'kyo', group:'Combo', words:[{w:'キョウリュウ',r:'kyouryuu',m:'dinosaur'},{w:'キョリ',r:'kyori',m:'distance'}] },
  { char:'シャ', romaji:'sha', group:'Combo', words:[{w:'シャツ',r:'shatsu',m:'shirt'},{w:'シャワー',r:'shawaa',m:'shower'}] },
  { char:'シュ', romaji:'shu', group:'Combo', words:[{w:'シュークリーム',r:'shuukuriimu',m:'cream puff'},{w:'シュート',r:'shuuto',m:'shoot'}] },
  { char:'ショ', romaji:'sho', group:'Combo', words:[{w:'ショッピング',r:'shoppingu',m:'shopping'},{w:'ショコラ',r:'shokora',m:'chocolate'}] },
  { char:'チャ', romaji:'cha', group:'Combo', words:[{w:'チャンス',r:'chansu',m:'chance'},{w:'チャンネル',r:'channeru',m:'channel'}] },
  { char:'チュ', romaji:'chu', group:'Combo', words:[{w:'チューリップ',r:'chuurippu',m:'tulip'},{w:'チューブ',r:'chuubu',m:'tube'}] },
  { char:'チョ', romaji:'cho', group:'Combo', words:[{w:'チョコレート',r:'chokoreeto',m:'chocolate'},{w:'チョーク',r:'chooku',m:'chalk'}] },
  { char:'ニャ', romaji:'nya', group:'Combo', words:[{w:'ニャンコ',r:'nyanko',m:'kitty'}] },
  { char:'ニュ', romaji:'nyu', group:'Combo', words:[{w:'ニュース',r:'nyuusu',m:'news'},{w:'ニュアンス',r:'nyuansu',m:'nuance'}] },
  { char:'ニョ', romaji:'nyo', group:'Combo', words:[{w:'ニョッキ',r:'nyokki',m:'gnocchi'}] },
  { char:'ヒャ', romaji:'hya', group:'Combo', words:[{w:'ヒャク',r:'hyaku',m:'hundred'}] },
  { char:'ヒュ', romaji:'hyu', group:'Combo', words:[{w:'ヒューズ',r:'hyuuzu',m:'fuse'},{w:'ヒューマン',r:'hyuuman',m:'human'}] },
  { char:'ヒョ', romaji:'hyo', group:'Combo', words:[{w:'ヒョウ',r:'hyou',m:'leopard/hail'},{w:'ヒョウタン',r:'hyoutan',m:'gourd'}] },
  { char:'ミャ', romaji:'mya', group:'Combo', words:[{w:'ミャンマー',r:'myanmaa',m:'Myanmar'}] },
  { char:'ミュ', romaji:'myu', group:'Combo', words:[{w:'ミュージック',r:'myuujikku',m:'music'},{w:'ミュージアム',r:'myuujiamu',m:'museum'}] },
  { char:'ミョ', romaji:'myo', group:'Combo', words:[{w:'ミョウガ',r:'myouga',m:'Japanese ginger'}] },
  { char:'リャ', romaji:'rya', group:'Combo', words:[{w:'リャクゴ',r:'ryakugo',m:'abbreviation'}] },
  { char:'リュ', romaji:'ryu', group:'Combo', words:[{w:'リュック',r:'ryukku',m:'backpack'},{w:'リュウ',r:'ryuu',m:'dragon'}] },
  { char:'リョ', romaji:'ryo', group:'Combo', words:[{w:'リョコウ',r:'ryokou',m:'travel'},{w:'リョウリ',r:'ryouri',m:'cooking'}] },
  { char:'ギャ', romaji:'gya', group:'Combo', words:[{w:'ギャグ',r:'gyagu',m:'gag/joke'},{w:'ギャラリー',r:'gyararii',m:'gallery'}] },
  { char:'ギュ', romaji:'gyu', group:'Combo', words:[{w:'ギュウニュウ',r:'gyuunyuu',m:'milk'},{w:'ギュウニク',r:'gyuuniku',m:'beef'}] },
  { char:'ギョ', romaji:'gyo', group:'Combo', words:[{w:'ギョウザ',r:'gyouza',m:'dumplings'},{w:'ギョウレツ',r:'gyouretsu',m:'queue'}] },
  { char:'ジャ', romaji:'ja',  group:'Combo', words:[{w:'ジャム',r:'jamu',m:'jam'},{w:'ジャケット',r:'jaketto',m:'jacket'}] },
  { char:'ジュ', romaji:'ju',  group:'Combo', words:[{w:'ジュース',r:'juusu',m:'juice'},{w:'ジュエリー',r:'juerii',m:'jewelry'}] },
  { char:'ジョ', romaji:'jo',  group:'Combo', words:[{w:'ジョギング',r:'jogingu',m:'jogging'},{w:'ジョーク',r:'jooku',m:'joke'}] },
  { char:'ビャ', romaji:'bya', group:'Combo', words:[{w:'ビャクヤ',r:'byakuya',m:'white night'}] },
  { char:'ビュ', romaji:'byu', group:'Combo', words:[{w:'ビュッフェ',r:'byuffe',m:'buffet'},{w:'ビュー',r:'byuu',m:'view'}] },
  { char:'ビョ', romaji:'byo', group:'Combo', words:[{w:'ビョウイン',r:'byouin',m:'hospital'},{w:'ビョウキ',r:'byouki',m:'illness'}] },
  { char:'ピャ', romaji:'pya', group:'Combo', words:[{w:'ピャノ',r:'pyano',m:'(variant)'}] },
  { char:'ピュ', romaji:'pyu', group:'Combo', words:[{w:'ピュア',r:'pyua',m:'pure'}] },
  { char:'ピョ', romaji:'pyo', group:'Combo', words:[{w:'ピョンピョン',r:'pyonpyon',m:'hopping'}] },
];
